### ISSUE TITLE
Update Rapidcheck and googletest for GCC 13.2.1 / CMake 3.27.7

### ISSUE THREAD

**Issue by WhiteCat6142** [dcdpr/libbech32#16]
Related : #9 and #15 

I could successfully compile libbech32 (applying the patch) on GCC 13.2.1 with Fedora.
At that time, I needed to add CMake option ‘-DLIBBECH32_BUILD_TESTS=OFF‘.
The reason is that those two test libraries are old for latest GCC and CMake.
I report this issue for the future reference and also I’ll help you if there is anything I can do.

**Comment by danpape** [comment]
Thanks, I noticed that too on my side. I'll get everything updated asap.

**Comment by danpape** [comment]
I was able to update both rapidcheck and googletest to the latest versions and built and tested everything on gcc 13 and 14 and clang 17 and 18 (and many older versions) with recent cmakes.

Can you try out the latest code and let me know if everything works for you? thank you

**Comment by WhiteCat6142** [comment]
I check the latest version, and it works. Thank you so much.
