### ISSUE TITLE
Update googletest to compile on modern clang versions

### ISSUE THREAD

**Issue by gpshead** [dcdpr/libbech32#9]
Please update test/googletest to at least https://github.com/google/googletest/commit/f7902802f1a61140e188223fb6d1c95925cbec4a to work around https://github.com/google/googletest/issues/3427.

Otherwise modern clang versions fail to build this with:

`libbech32/test/googletest/googlemock/include/gmock/gmock-actions.h:455:3: error: definition of implicit copy constructor for 'PolymorphicAction<testing::internal::ReturnNullAction>' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]`
`  GTEST_DISALLOW_ASSIGN_(PolymorphicAction);`

**Comment by danpape** [comment]
Thanks for the report. Looks like I need to upgrade my copies of clang. I'll reply back here when I get it fixed.

**Comment by danpape** [comment]
@gpshead We updated our embedded googletest with #10. We built and tested with clang++ 10, 11, 12, 13, and 14. Can you update on your side and make sure it works for you? Thanks.

**Comment by danpape** [comment]
Hey @gpshead any chance you can verify to close this issue? Thanks.

**Comment by gpshead** [comment]
thanks!
